version: "3.9"

services:
  mongodb:
    container_name: heroes-db
    image: mongo:latest
    networks:
      - heroes-net
    ports:
      - "11008:27017"
    environment:
      MONGO_INITDB_ROOT_USERNAME: "admin"
      MONGO_INITDB_DATABASE: "admin"
      MONGO_INITDB_ROOT_PASSWORD: "password"
    volumes:
      - ./mongo/mongo-init.js:/docker-entrypoint-initdb.d/mongo-init.js
      -
networks:
  heroes-net:
    driver: bridge